plugins {
    id 'java'
}
group = 'secret.kinetic'
version = '1.8.9'
java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}
tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 8
}
jar {
    archiveBaseName.set('Kinetic')
    archiveClassifier.set('')
    archiveVersion.set('')
    manifest {
        attributes('Main-Class': 'secret.kinetic.launcher.KineticLauncher')
    }
}
